{
    "openapi": "3.1.0",
    "info": {
        "title": "OpenAPI Developer Portal",
        "description": "A sample API that uses a plant store as an example to demonstrate features in the OpenAPI specification",
        "license": {
            "name": "MIT"
        },
        "version": "1.0.0"
    },
    "servers": [
        {
            "url": "https://628e-202-53-12-234.ngrok-free.app"
        }
    ],
    "security": [
        {
            "bearerAuth": []
        }
    ],
    "paths": {
        "/auth/v1/users": {
            "get": {
                "description": "Returns all users from the system that the user has access to",
                "responses": {
                    "200": {
                        "description": "Get User Details",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/components/schemas/User"
                                    }
                                },
                                "example": [
                                    {
                                        "message": "User Listed Successfully",
                                        "data": {
                                            "_id": "5f43a9f4f36d287b3f9e6b4b",
                                            "teamId": "5f43a9f4f36d287b3f9e6b3h",
                                            "firstName": "John",
                                            "lastName": "Doe",
                                            "email": "john.doe@example.com",
                                            "password": "securepassword123",
                                            "createdAt": "2025-02-06T10:05:15.793Z",
                                            "updatedAt": "2025-02-07T10:05:15.793Z"
                                        }
                                    },
                                    {
                                        "_id": "5f43a9f4f36d287b3f9e6b4c",
                                        "teamId": "5f43a9f4f36d287b3f9e6b3h",
                                        "firstName": "Jane",
                                        "lastName": "Smith",
                                        "email": "jane.smith@example.com",
                                        "password": "anotherpassword456",
                                        "createdAt": "2025-02-07T10:05:15.793Z",
                                        "updatedAt": "2025-02-07T10:05:15.793Z"
                                    }
                                ]
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a new user",
                "requestBody": {
                    "description": "Plant to add to the store",
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/User"
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "200": {
                        "description": "User is created successfully",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/NewUser"
                                },
                                "example": {
                                    "message": "User Created Successfully",
                                    "data": {
                                        "_id": "5f43a9f4f36d287b3f9e6b4b",
                                        "teamId": "5f43a9f4f36d287b3f9e6b3h",
                                        "firstName": "John",
                                        "lastName": "Doe",
                                        "email": "john.doe@example.com",
                                        "password": "securepassword123",
                                        "createdAt": "2025-02-07T10:05:15.793Z",
                                        "updatedAt": "2025-02-07T10:05:15.793Z"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/auth/v1/users/{id}": {
            "get": {
                "description": "Retrieve a single user by ID",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "ID of the user to retrieve",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User details retrieved successfully",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/User"
                                },
                                "example": {
                                    "message": "User Listed Successfully",
                                    "data": {
                                        "_id": "67c97464ae3d19dc2bbff05d",
                                        "teamId": "67a2ea1d828c9098134e7b92",
                                        "firstName": "john",
                                        "lastName": "Doe",
                                        "email": "john.doe@example.com",
                                        "password": "$2b$10$I9NsnI5BWvwXXFAGLnsAs.DSUNKGoVHEYPkx.lxhT12W7rjypM/pG",
                                        "createdAt": "2025-03-06T10:09:40.301Z",
                                        "updatedAt": "2025-03-25T08:26:23.653Z",
                                        "__v": 0
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "patch": {
                "description": "Update a user by ID",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "ID of the user to update",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "requestBody": {
                    "description": "User data to update",
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "firstName": {
                                        "type": "string",
                                        "description": "First name of the user"
                                    },
                                    "lastName": {
                                        "type": "string",
                                        "description": "Last name of the user"
                                    },
                                    "email": {
                                        "type": "string",
                                        "description": "Email address of the user",
                                        "format": "email"
                                    }
                                }
                            },
                            "example": {
                                "firstname": "john",
                                "lastname": "Doe",
                                "email": "john.doe@example.com"
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "200": {
                        "description": "User updated successfully",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/User"
                                },
                                "example": {
                                    "_id": "67c97464ae3d19dc2bbff05d",
                                    "teamId": "67a2ea1d828c9098134e7b92",
                                    "firstName": "john",
                                    "lastName": "Doe",
                                    "email": "john.doe@example.com",
                                    "password": "$2b$10$I9NsnI5BWvwXXFAGLnsAs.DSUNKGoVHEYPkx.lxhT12W7rjypM/pG",
                                    "createdAt": "2025-03-06T10:09:40.301Z",
                                    "updatedAt": "2025-03-25T08:26:23.653Z",
                                    "__v": 0
                                }
                            }
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a user by ID",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "ID of the user to delete",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User details retrieved successfully",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/User"
                                },
                                "example": {
                                    "message": "User is Deleted Successfully"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/docs/v1/uploads": {
            "get": {
                "description": "Returns all users from the system that the user has access to",
                "parameters": [
                    {
                        "name": "limit",
                        "in": "query",
                        "description": "The number of items to return per page",
                        "required": false,
                        "schema": {
                            "type": "integer",
                            "default": 5
                        }
                    },
                    {
                        "name": "page",
                        "in": "query",
                        "description": "The page number to retrieve",
                        "required": false,
                        "schema": {
                            "type": "integer",
                            "default": 1
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Files Details",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/components/schemas/UploadResponse"
                                    }
                                },
                                "example": {
                                    "message": "Files Listed Successfully",
                                    "data": [
                                        {
                                            "_id": "67b826d08e3763327b9ab36d",
                                            "teamId": "67a2ea1d828c9098134e7b92",
                                            "originalName": "0.5_0.05_3.0_female_male_no_overlap_bnc_0_1.wav",
                                            "fileType": "audio file",
                                            "status": "completed",
                                            "createdAt": "2025-02-21T07:10:08.707Z",
                                            "updatedAt": "2025-02-21T07:10:19.297Z",
                                            "__v": 0,
                                            "filename": "e2edcfee-263a-4c89-b3f5-28be5b293df9-0.5_0.05_3.0_female_male_no_overlap_bnc_0_1.wav",
                                            "path": "https://sample/uploads/e2edcfee-263a-4c89-b3f5-28be5b293df9-0.5_0.05_3.0.wav"
                                        },
                                        {
                                            "_id": "67b826d08e3133327b9ab36d",
                                            "teamId": "67a2ea1d828c9098134e7b92",
                                            "originalName": "0.5_0.05_3.0_female_male_no_overlap_bnc_0_1.wav",
                                            "fileType": "audio file",
                                            "status": "completed",
                                            "createdAt": "2025-02-21T07:10:08.707Z",
                                            "updatedAt": "2025-02-21T07:10:19.297Z",
                                            "__v": 0,
                                            "filename": "e2edcfee-263a-4c89-b3f5-28be5b293df9-0.5_0.05_3.0_female_male_no_overlap_bnc_0_1.wav",
                                            "path": "https://sample/uploads/e2edcfee-263a-4c89-b3f5-28be5b293df9-0.5_0.05_3.0.wav"
                                        }
                                    ]
                                }
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Upload a file",
                "parameters": [
                    {
                        "name": "mvns",
                        "in": "query",
                        "description": "The number of items to return per page",
                        "required": false,
                        "schema": {
                            "type": "integer",
                            "default": 0
                        }
                    },
                    {
                        "name": "dgc",
                        "in": "query",
                        "required": false,
                        "schema": {
                            "type": "integer",
                            "default": 0
                        }
                    },
                    {
                        "name": "bvs",
                        "in": "query",
                        "required": false,
                        "schema": {
                            "type": "integer",
                            "default": 0
                        }
                    }
                ],
                "requestBody": {
                    "description": "File to upload",
                    "content": {
                        "multipart/form-data": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "file": {
                                        "type": "string",
                                        "format": "binary",
                                        "description": "The file to upload"
                                    }
                                },
                                "required": [
                                    "file"
                                ]
                            },
                            "encoding": {
                                "file": {
                                    "contentType": "application/octet-stream"
                                }
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "200": {
                        "description": "File is uploaded successfully",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Upload"
                                },
                                "example": {
                                    "message": "File is uploaded successfully and will be processed shortly."
                                }
                            }
                        }
                    }
                }
            }
        },
        "/docs/v1/uploads/{id}": {
            "get": {
                "description": "Download a file by ID",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "ID of the file to download",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User details retrieved successfully",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/download"
                                },
                                "example": {
                                    "status": true,
                                    "message": "Signed URL generated successfully.",
                                    "signedUrl": "https://sample.com/uploads/e2edcfee-263a-4c89-b3f5-28be5b293df9-0.5_0.05_"
                                }
                            }
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a user by ID",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "ID of the user to delete",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Audio file is deleted successfully",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/DeleteUpload"
                                },
                                "example": {
                                    "status": true,
                                    "message": "Audio file deleted successfully."
                                }
                            }
                        }
                    }
                }
            }
        },
        "/auth/v1/apikeys": {
            "get": {
                "description": "Returns all api keys from the system that the user has access to",
                "responses": {
                    "200": {
                        "description": "Api Keys Details",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/components/schemas/ApiKeys"
                                    }
                                },
                                "example": {
                                    "message": "Api keys are Listed Successfully",
                                    "data": [
                                        {
                                            "_id": "67c52a1526865c41a282c4e9",
                                            "teamId": "67a2ea1d828c9098134e7b92",
                                            "name": "Suresh",
                                            "key": "3289e233-93f7-411e-9d06-308c26fc278f",
                                            "createdAt": "2025-03-03T03:58:10.357+00:00",
                                            "expiresAt": "2025-03-10T04:03:33.131+00:00",
                                            "uuid": "67af1bcea4f8dca74f0d51b0",
                                            "isPublic": true
                                        },
                                        {
                                            "_id": "67c52a1526865c41a282c4e0",
                                            "teamId": "67a2ea1d828c9098134e7b91",
                                            "name": "John",
                                            "key": "3289e233-93f7-411e-9d06-308c26fc278g",
                                            "createdAt": "2025-03-03T03:58:10.357+00:00",
                                            "expiresAt": "2025-03-10T04:03:33.131+00:00",
                                            "uuid": "67af1bcea4f8dca74f0d51b0",
                                            "isPublic": true
                                        }
                                    ]
                                }
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new API key",
                "requestBody": {
                    "description": "API key details to be created",
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "name": {
                                        "type": "string",
                                        "description": "Name of the API key."
                                    },
                                    "isPublic": {
                                        "type": "boolean",
                                        "description": "Whether the API key is public."
                                    },
                                    "allowedOrigins": {
                                        "type": "array",
                                        "items": {
                                            "type": "string"
                                        },
                                        "description": "List of allowed origins (only required if isPublic is false)."
                                    }
                                },
                                "required": [
                                    "name",
                                    "isPublic"
                                ],
                                "oneOf": [
                                    {
                                        "properties": {
                                            "isPublic": {
                                                "enum": [
                                                    true
                                                ]
                                            }
                                        },
                                        "required": []
                                    },
                                    {
                                        "properties": {
                                            "isPublic": {
                                                "enum": [
                                                    false
                                                ]
                                            },
                                            "allowedOrigins": {
                                                "type": "array",
                                                "items": {
                                                    "type": "string"
                                                },
                                                "minItems": 1,
                                                "description": "Allowed origins must be provided if the API key is not public."
                                            }
                                        },
                                        "required": [
                                            "allowedOrigins"
                                        ]
                                    }
                                ]
                            },
                            "example": {
                                "name": "Suresh",
                                "isPublic": true
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "200": {
                        "description": "API Key created successfully",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "_id": {
                                            "type": "string"
                                        },
                                        "teamId": {
                                            "type": "string"
                                        },
                                        "name": {
                                            "type": "string"
                                        },
                                        "key": {
                                            "type": "string"
                                        },
                                        "createdAt": {
                                            "type": "string",
                                            "format": "date-time"
                                        },
                                        "expiresAt": {
                                            "type": "string",
                                            "format": "date-time"
                                        },
                                        "uuid": {
                                            "type": "string"
                                        },
                                        "isPublic": {
                                            "type": "boolean"
                                        }
                                    }
                                },
                                "example": {
                                    "message": "API key is created successfully",
                                    "data": {
                                        "_id": "67c52a1526865c41a282c4e9",
                                        "teamId": "67a2ea1d828c9098134e7b92",
                                        "name": "Suresh",
                                        "key": "3289e233-93f7-411e-9d06-308c26fc278f",
                                        "createdAt": "2025-03-03T03:58:10.357+00:00",
                                        "expiresAt": "2025-03-10T04:03:33.131+00:00",
                                        "uuid": "67af1bcea4f8dca74f0d51b0",
                                        "isPublic": true
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/auth/v1/apikeys/{id}": {
            "get": {
                "description": "fetch a apikey by ID",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "ID of the file to download",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Apikey details retrieved successfully",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ApiKeys"
                                },
                                "example": {
                                    "message": "API key is listed successfully",
                                    "data": {
                                        "_id": "67c52a1526865c41a282c4e9",
                                        "teamId": "67a2ea1d828c9098134e7b92",
                                        "name": "Suresh",
                                        "key": "3289e233-93f7-411e-9d06-308c26fc278f",
                                        "createdAt": "2025-03-03T03:58:10.357+00:00",
                                        "expiresAt": "2025-03-10T04:03:33.131+00:00",
                                        "uuid": "67af1bcea4f8dca74f0d51b0",
                                        "isPublic": true
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "patch": {
                "description": "Update a user by ID",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "ID of the user to update",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "requestBody": {
                    "description": "API key details to be created",
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "name": {
                                        "type": "string",
                                        "description": "Name of the API key."
                                    },
                                    "isPublic": {
                                        "type": "boolean",
                                        "description": "Whether the API key is public."
                                    },
                                    "allowedOrigins": {
                                        "type": "array",
                                        "items": {
                                            "type": "string"
                                        },
                                        "description": "List of allowed origins (only required if isPublic is false)."
                                    },
                                    "expiresAt": {
                                        "type": "string",
                                        "format": "date-time",
                                        "description": "Expiration date of the API key."
                                    }
                                },
                                "required": [
                                    "name",
                                    "isPublic"
                                ],
                                "oneOf": [
                                    {
                                        "properties": {
                                            "isPublic": {
                                                "enum": [
                                                    true
                                                ]
                                            }
                                        },
                                        "required": []
                                    },
                                    {
                                        "properties": {
                                            "isPublic": {
                                                "enum": [
                                                    false
                                                ]
                                            },
                                            "allowedOrigins": {
                                                "type": "array",
                                                "items": {
                                                    "type": "string"
                                                },
                                                "minItems": 1,
                                                "description": "Allowed origins must be provided if the API key is not public."
                                            }
                                        },
                                        "required": [
                                            "allowedOrigins"
                                        ]
                                    }
                                ]
                            },
                            "example": {
                                "name": "Suresh",
                                "isPublic": true
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "200": {
                        "description": "User updated successfully",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ApiKeys"
                                },
                                "example": {
                                    "message": "API key is updated successfully",
                                    "data": {
                                        "_id": "67c52a1526865c41a282c4e9",
                                        "teamId": "67a2ea1d828c9098134e7b92",
                                        "name": "Suresh",
                                        "key": "3289e233-93f7-411e-9d06-308c26fc278f",
                                        "createdAt": "2025-03-03T03:58:10.357+00:00",
                                        "expiresAt": "2025-03-10T04:03:33.131+00:00",
                                        "uuid": "67af1bcea4f8dca74f0d51b0",
                                        "isPublic": true
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a user by ID",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "ID of the user to delete",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Api key is deleted successfully",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ApiKeys"
                                },
                                "example": {
                                    "message": "Api key is deleted successfully.",
                                    "data": {
                                        "_id": "67c52a1526865c41a282c4e9",
                                        "teamId": "67a2ea1d828c9098134e7b92",
                                        "name": "Suresh",
                                        "key": "3289e233-93f7-411e-9d06-308c26fc278f",
                                        "createdAt": "2025-03-03T03:58:10.357+00:00",
                                        "expiresAt": "2025-03-10T04:03:33.131+00:00",
                                        "uuid": "67af1bcea4f8dca74f0d51b0",
                                        "isPublic": true
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "webhooks": {
        "/plant/webhook": {
            "post": {
                "description": "Information about a new plant added to the store",
                "requestBody": {
                    "description": "Plant added to the store",
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/NewUser"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Return a 200 status to indicate that the data was received successfully"
                    }
                }
            }
        }
    },
    "components": {
        "schemas": {
            "User": {
                "required": [
                    "firstName",
                    "lastName",
                    "email",
                    "password"
                ],
                "type": "object",
                "properties": {
                    "firstName": {
                        "description": "The first name of the user",
                        "type": "string"
                    },
                    "lastName": {
                        "description": "The last name of the user",
                        "type": "string"
                    },
                    "email": {
                        "description": "The email of the user",
                        "type": "string"
                    },
                    "password": {
                        "description": "The password of the user",
                        "type": "string"
                    }
                }
            },
            "NewUser": {
                "allOf": [
                    {
                        "$ref": "#/components/schemas/User"
                    },
                    {
                        "required": [
                            "id"
                        ],
                        "type": "object",
                        "properties": {
                            "id": {
                                "description": "Identification number of the plant",
                                "type": "integer",
                                "format": "int64"
                            },
                            "teamId": {
                                "description": "Team ID that the user belongs to",
                                "type": "integer",
                                "format": "int64"
                            },
                            "createdAt": {
                                "description": "Date and time when the User was added to the store",
                                "type": "string",
                                "format": "date-time"
                            },
                            "updatedAt": {
                                "description": "Date and time when the user was last updated",
                                "type": "string",
                                "format": "date-time"
                            }
                        }
                    }
                ]
            },
            "Upload": {
                "required": [
                    "file"
                ],
                "properties": {
                    "file": {
                        "type": "string",
                        "format": "binary"
                    }
                }
            },
            "UploadResponse": {
                "required": [
                    "id",
                    "status"
                ],
                "type": "object",
                "properties": {
                    "id": {
                        "type": "string",
                        "format": "uuid"
                    },
                    "teamId": {
                        "type": "string",
                        "format": "uuid"
                    },
                    "originalName": {
                        "type": "string"
                    },
                    "fileType": {
                        "type": "string"
                    },
                    "status": {
                        "type": "string",
                        "enum": [
                            "uploaded",
                            "processing",
                            "completed"
                        ]
                    },
                    "fileName": {
                        "type": "string"
                    },
                    "path": {
                        "type": "string"
                    },
                    "createdAt": {
                        "description": "Date and time when the File was uploaded",
                        "type": "string",
                        "format": "date-time"
                    }
                }
            },
            "DeleteUpload": {
                "properties": {
                    "status": {
                        "type": "boolean"
                    },
                    "message": {
                        "type": "string"
                    }
                }
            },
            "download": {
                "required": [
                    "status",
                    "message",
                    "signedUrl"
                ],
                "type": "object",
                "properties": {
                    "status": {
                        "type": "boolean"
                    },
                    "message": {
                        "type": "string"
                    },
                    "signedUrl": {
                        "type": "string"
                    }
                }
            },
            "ApiKeys": {
                "required": [
                    "id",
                    "key",
                    "name",
                    "teamId",
                    "uuid",
                    "isPublic",
                    "createdAt",
                    "expiresAt"
                ],
                "type": "object",
                "properties": {
                    "id": {
                        "type": "string"
                    },
                    "key": {
                        "type": "string"
                    },
                    "teamId": {
                        "type": "string"
                    },
                    "uuid": {
                        "type": "string"
                    },
                    "isPublic": {
                        "type": "boolean"
                    },
                    "createdAt": {
                        "type": "string"
                    },
                    "expiresAt": {
                        "type": "string"
                    }
                }
            },
            "createApikey": {
                "required": [
                    "name",
                    "isPublic"
                ],
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "isPublic": {
                        "type": "boolean"
                    }
                }
            },
            "Error": {
                "required": [
                    "error",
                    "message"
                ],
                "type": "object",
                "properties": {
                    "error": {
                        "type": "integer",
                        "format": "int32"
                    },
                    "message": {
                        "type": "string"
                    }
                }
            }
        },
        "securitySchemes": {
            "bearerAuth": {
                "type": "http",
                "scheme": "bearer"
            }
        }
    }
}